apiVersion: v1
kind: Pod
metadata:
  name: service1-api
  labels:
    Application: service1
    label: api 
  annotations: {
    "opencontrail.org/network" : '{"domain":"default-domain", "project": "test-project", "name":"VN1"}'
  }
spec:
  containers:
  - name: service1-api
    image: cirros
