apiVersion: v1
kind: Pod
metadata:
  name: service1-web
  labels:
    Application: service1
    label: web
  annotations: {
    "opencontrail.org/network" : '{"domain":"default-domain", "project": "test-project", "name":"VN1"}'
  }
spec:
  containers:
  - name: service1-web
    image: cirros
